#!/usr/bin/python3

import asyncio
import logging
import sys

from pyeep.aio import AIOApp, AIOComponent
from pyeep.gtk import GtkApp

log = logging.getLogger(__name__)


class AIOTick(AIOComponent):
    async def run(self):
        while not self.shutting_down:
            log.info("AIO tick")
            await asyncio.sleep(1)


class App(GtkApp, AIOApp):
    def __init__(self, *args, **kw):
        super().__init__(*args, **kw)
        self.add_component(AIOTick(name="aio_tick"))


def main():
    parser = App.argparser("Test AIO apps")
    args = parser.parse_args()

    with App(args, title="Test Pyeep Gtk app") as app:
        app.main()


if __name__ == "__main__":
    sys.exit(main())
