#!/usr/bin/python3

import asyncio
import sys
import time

from pyeep.aio import AIOApp, AIOComponent


class AIOTick(AIOComponent):
    async def run(self):
        while not self.shutting_down:
            print("AIO tick")
            await asyncio.sleep(1)


class App(AIOApp):
    def __init__(self, *args, **kw):
        super().__init__(*args, **kw)
        self.add_component(AIOTick("aio_tick"))

    def main_loop(self):
        while not self.shutting_down:
            print("Main loop tick")
            time.sleep(1)


def main():
    parser = App.argparser("Test AIO apps")
    args = parser.parse_args()

    with App(args) as app:
        app.main()


if __name__ == "__main__":
    sys.exit(main())
