from typing import TYPE_CHECKING, NotRequired, Unpack, override

from pyeep.models.messages import Broadcast, Command, Event

from .node import Node, NodeArgs

if TYPE_CHECKING:
    from .hub import Hub


class ComponentArgs(NodeArgs):
    """Arguments for Node constructor."""

    hub: "Hub"
    namespace: NotRequired[str | None]


class Component(Node):
    """
    Pyeep component.

    A component can generate events and receive commands.
    """

    def __init__(
        self,
        *,
        hub: "Hub",
        namespace: str | None = None,
        **kwargs: Unpack[NodeArgs],
    ) -> None:
        """
        Initialize the component.

        You need to call ``hub.add_component`` after initialization to add the
        component to the hub.
        """
        super().__init__(**kwargs)
        self.hub = hub
        self.namespace = namespace or self.hub.routing_key

    @override
    def get_routing_key(self) -> str:
        return f"{self.namespace}.{self.name}"

    @override
    async def send_event(self, msg: Event) -> None:
        """Send an event generated by a component."""
        await self.hub.outbound_event(self._add_routing_key(msg))

    @override
    async def send_broadcast(self, msg: Broadcast) -> None:
        """Send a broadcast generated by a component."""
        await self.hub.outbound_broadcast(self._add_routing_key(msg))

    @override
    async def send_command(self, msg: Command) -> None:
        """Send a command generated by a component."""
        await self.hub.outbound_command(self._add_routing_key(msg))


class PublicComponent(Component):
    """Component whose existance gets advertised to remote hubs."""
