import abc
import asyncio
from typing import TYPE_CHECKING, Unpack, override

from pyeep.models.messages import (
    Broadcast,
    Command,
    Event,
    RoutingKey,
    expand_routing_keys,
)

from .node import Node, NodeArgs

if TYPE_CHECKING:
    from .component import Component


class HubArgs(NodeArgs):
    """Arguments for Hub constructor."""


class Hub(Node, abc.ABC):
    """Coordinate pyeep components."""

    def __init__(self, **kwargs: Unpack[NodeArgs]) -> None:
        super().__init__(**kwargs)
        self.components: dict[str, "Component"] = {}

    @override
    def get_routing_key(self) -> RoutingKey:
        return self.name

    async def advertise_component_added(self, component: "Component") -> None:
        """Advertise that a new component has been added."""
        # Do nothing by default

    async def advertise_component_removed(self, component: "Component") -> None:
        """Advertise that a new component is about to be removed."""
        # Do nothing by default

    async def add_component(self, component: "Component") -> None:
        """Add a component to the hub."""
        rk = component.routing_key
        if rk in self.components:
            self.log.warning("Component %s replaced", rk)
        self.components[rk] = component
        await self.start_task(component.main_task())
        await self.advertise_component_added(component)

    async def remove_component(self, component: "Component") -> None:
        """Remove a component from the hub."""
        rk = component.routing_key
        if rk not in self.components:
            self.log.warning("Ignoring removal of nonexisting component %s", rk)
        await self.advertise_component_removed(component)
        del self.components[rk]

    @override
    async def send_event(self, msg: Event) -> None:
        """Send an event generated by a component."""
        await self.outbound_event(self._add_routing_key(msg))

    @override
    async def send_broadcast(self, msg: Broadcast) -> None:
        """Send a broadcast generated by a component."""
        await self.outbound_broadcast(self._add_routing_key(msg))

    @override
    async def send_command(self, msg: Command) -> None:
        """Send a command generated by a component."""
        await self.outbound_command(self._add_routing_key(msg))

    @abc.abstractmethod
    async def outbound_event(self, msg: Event) -> None:
        """Process an outbound event generated by a component."""

    @abc.abstractmethod
    async def outbound_broadcast(self, msg: Broadcast) -> None:
        """Process an outbound broadcast generated by a component."""

    @abc.abstractmethod
    async def outbound_command(self, msg: Command) -> None:
        """Process an outbound command generated by a component."""

    async def inbound_event(self, msg: Event) -> None:
        """Process an inbound event."""
        async with asyncio.TaskGroup() as tg:
            for component in self.components.values():
                tg.create_task(component.receive(msg))

    async def inbound_broadcast(self, msg: Broadcast) -> None:
        """Process an inbound broadcast."""
        async with asyncio.TaskGroup() as tg:
            for component in self.components.values():
                tg.create_task(component.receive(msg))

    async def inbound_command(self, msg: Command) -> None:
        """Process an inbound command."""
        async with asyncio.TaskGroup() as tg:
            for dest in expand_routing_keys(msg.dst):
                if (component := self.components.get(dest)) is None:
                    continue
                tg.create_task(component.receive(msg))
