import abc
import asyncio
import logging
from collections.abc import Coroutine
from functools import cached_property
from typing import TypedDict, Unpack, override

from pyeep.models.messages import Broadcast, Command, Event, Message, RoutingKey


class NodeArgs(TypedDict):
    """Arguments for Node constructor."""

    name: str


class Node(abc.ABC):
    """
    Pyeep node.

    This is a base class for all named building blocks in a pyeep system.
    """

    def __init__(self, **kwargs: Unpack[NodeArgs]) -> None:
        """
        Initialize a node.

        :param name: node name
        """
        self.name = kwargs["name"]
        self.log = logging.getLogger(self.get_logger_name())

    @cached_property
    def routing_key(self) -> RoutingKey:
        """Routing key for this node."""
        return self.get_routing_key()

    def get_logger_name(self) -> str:
        """Return the name to use for logging."""
        return self.name

    @abc.abstractmethod
    def get_routing_key(self) -> RoutingKey:
        """Return the routing key for this node."""

    @override
    def __str__(self) -> str:
        return self.name

    def _add_routing_key[M: Message](self, msg: M) -> M:
        """Return a copy of Message with our routing key added."""
        if msg.src is not None:
            raise ValueError(
                "trying to send a message with an existing sender key"
            )
        return msg.model_copy(update={"src": self.routing_key})

    async def receive(self, message: Message) -> None:
        """Deliver a message to this component."""
        # Do nothing by default

    @abc.abstractmethod
    async def send_event(self, msg: Event) -> None:
        """Send an event generated by a component."""

    @abc.abstractmethod
    async def send_broadcast(self, msg: Broadcast) -> None:
        """Send a broadcast generated by a component."""

    @abc.abstractmethod
    async def send_command(self, msg: Command) -> None:
        """Send a command generated by a component."""

    def supervise_coroutine[T](
        self, coro: Coroutine[None, None, T]
    ) -> Coroutine[None, None, T | None]:
        """
        Supervise a coroutine.

        This will log any exceptions raised other than CancelledError.
        """

        async def wrapper() -> T | None:
            cancelled: asyncio.CancelledError | None = None
            try:
                return await coro
            except asyncio.CancelledError as cexc:
                cancelled = cexc
            except Exception as exc:
                self.log.error(
                    "Coroutine %r failed: %s", coro, exc, exc_info=exc
                )
            if cancelled is not None:
                raise cancelled
            return None

        return wrapper()
